### PR TITLE
Add Switzerland's virtual event

### PR DESCRIPTION
**Pull request by escodebar**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @escodebar , the date on either your website or this PR is wrong. I fixed it on the PR, but wondered if the wizard filled it in (that'd be a bug 😱) or if it's your typo?

**Comment by escodebar** [comment]
Hello @rradczewski,

It was for sure my error. I just double checked the wizard, and the week starts by default on Sunday instead of Monday, making the second last column a Friday instead of the Saturday :smiley: 

Thanks for fixing the date! :heart:

**Comment by rradczewski** [comment]
Oh I'm glad then. I think we spent most of our efforts on the new website on wrapping our heads around timezones! :grimacing: 

Merged, and thanks for submitting your event!

**Comment by rradczewski** [comment]
Hi, we hope you had a great Global Day Of Coderetreat! We're trying to understand how the current situation has affected the events this year and how we could support you next year for #GDCR2021.

For this purpose, we created [a seven-questions-survey](https://docs.google.com/forms/d/e/1FAIpQLSdi8fmw42s8tXtVneJH5VcRpB9vMf35gJ2APw4PijQ0-Gq_Ww/viewform?usp=sf_link) (anonymously, all optional, single page) for those who organized an event this year. It would help us tremendously if you could fill it out. It doesn't take long, promise :smile: 

Thanks and all the best,
Raimo

**Pull request merged**
