### PR TITLE
Karlsruhe added

### PR DESCRIPTION
**Pull request by pfichtner**

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Hi @pfichtner, thanks for your contribution! :tada: 

Please, it cannot be merged for these reasons:

* `date` is missing.
* `timezone` and `utcOffset` are not necessary.

You can see an example at [this template](https://github.com/coderetreat/coderetreat.org/blob/master/_data/events_gdcr2019/TEMPLATE).

Thanks!

**Comment by pfichtner** [comment]
Issues fixed

**Comment by rachelcarmena** [comment]
Thnaks @pfichtner ! Everything is ok now. 
Merged! :tada:

**Comment by rachelcarmena** [comment]
Thanks @pfichtner ! Everything is ok now.
Merged! :tada:

**Pull request merged**
