### PR TITLE
add calgary gdcr2019

### PR DESCRIPTION
**Pull request by tonytvo**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi, can you please fill in the dates and fix the moderators and sponsors fields?

**Comment by tonytvo** [comment]
Yes will do once I have some time after work

**Comment by tonytvo** [comment]
@rradczewski the fields are fixed, can  you merged this?

**Comment by rradczewski** [comment]
Hi @tonytvo , looks like the meetup event isn't published yet. Can you ping me once that's done? Otherwise there's no way for people to RSVP, so publishing on the map is a bit pointless. :)

**Comment by tonytvo** [comment]
@rradczewski I have published the meetup event, let me know if there's something else I need to do

**Comment by rradczewski** [comment]
Hmm not sure if it's a glitch in meetup, but following the url you provided ([https://www.meetup.com/Calgary-Software-Crafters/events/266157163](https://www.meetup.com/Calgary-Software-Crafters/events/266157163)) leads to your main meetup page with no scheduled event being listed. Am I missing something?

**Comment by tonytvo** [comment]
long story short, due to miscommunication, it is taken down, I have updated the meetup url, @rradczewski  can you take a look at it again?

**Comment by rradczewski** [comment]
Now that looks good, thanks!

**Pull request merged**
