### PR TITLE
switzerland 2022 zuerich event

### PR DESCRIPTION
**Pull request by AndrewMagerman**

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @AndrewMagerman , looks like that file doesn't contain an event :monocle_face: Happy to hear Switzerland is running an event though!

**Comment by AndrewMagerman** [comment]
Hi Raimo,

That's weird, I used the 'download JSON' option and it saved a garbled version of it. I've corrected this by copy-pasting the generated json code into it.

Best Regards,
Andrew Magerman

Magerman GmbH, Im Marbach 53, 8800 Thalwil, Tel: +41 79 831 83 13
http://www.magerman.com

**Comment by rradczewski** [comment]
That's weird indeed. Could you give me your browser/browser-extensions/operating-system specs? Worth taking a look there!

**Comment by rradczewski** [comment]
Had to change the encoding to UTF8 (without BOM), should be good now! Thanks

**Comment by AndrewMagerman** [comment]
Smooth. That was the nerdiest registration i have ever done

**Pull request merged**
