### PR TITLE
Added one remote GDCR from Spain

### PR DESCRIPTION
**Pull request by ydarias**
Added a remote event, for 2019, managed from Spain.

### CODE REVIEW

**Comment by rradczewski** [comment]
Hi @ydarias, thanks for submitting the event! We support virtual events ([invision hosted one last year](https://github.com/coderetreat/coderetreat.org/blob/master/_data/events_gdcr2018/virtual_invision.json#L2)), I'll update your PR right after this comment to reflect that.

Furthermore, I think I'd leave this PR open until you have a way for people to sign up for the event – otherwise there's little information about the event so far. Feel free to update it as soon as you have a sign up page!

**Comment by rachelcarmena** [comment]
@ydarias, hi friend!! I've just seen the new section "Cómo puedo participar" (how to participate). Thanks and welcome!! :tada:

**Comment by rachelcarmena** [comment]
And please, let us know when you have a facilitator. Thanks!! :clap:

**Comment by rachelcarmena** [comment]
:point_right: [Tweet link](https://twitter.com/coderetreat/status/1180530037537288192)

**Comment by ydarias** [comment]
Thank you @rachelcarmena ... I will add the facilitators as soon as possible :-)

**Pull request merged**
