### PR TITLE
Add Hexad Berlin

### PR DESCRIPTION
**Pull request by connect2nelson**
Add event for GDCR Berlin, hosted by Hexad Gmbh in partnership with Volkswagen Digital:Lab

### CODE REVIEW

**Comment by rradczewski** [comment]
Already taken care of in #635 :+1:

**Comment by rradczewski** [comment]
But if there's another event, the URL seems to be wrong. This one is pointing to an eventbrite event on Friday 🤔

**Comment by connect2nelson** [comment]
Updated the URL to have a  new meetup link :). Thanks for pointing it out.

**Comment by rradczewski** [comment]
Excellent, welcome!

**Pull request merged**
