### PR TITLE
Add 48 Hour Coderetreat

### PR DESCRIPTION
**Pull request by gregorriegler**

### CODE REVIEW

**Comment by rradczewski** [comment]
Thanks @gregorriegler , but what's that Vienna coderetreat about?

**Comment by gregorriegler** [comment]
It's strange I still have this as a commit. I think this was already in last year

**Comment by gregorriegler** [comment]
Yes, that's already in. I dunno. I messed something up in my fork I guess.

**Comment by gregorriegler** [comment]
I'm going to fix it

**Pull request closed without merging**
